# Generated by Django 3.2.8 on 2021-10-06 20:35

from django.db import migrations, models
import django.db.models.deletion
from system.migrations import MoveModelsMigration


class Migration(MoveModelsMigration):
    initial = True

    dependencies = [
        ('first', '0004_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=180)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first.post')),
            ],
        ),
    ]
