# Generated by Django 3.2.8 on 2021-10-05 11:49

from django.db import migrations, models
import django.db.models.deletion


def get_content_type_sql(model_names: [str], old_app: str, new_app: str):
    sql = ''
    for model in model_names:
        sql += f'''
            UPDATE django_content_type SET app_label = '{new_app}' 
            WHERE app_label='{old_app}' AND model='{model}';
        '''
    return sql


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('first', '0004_move_comment'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(get_content_type_sql(['comment'], 'first', 'comments'))
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Comment',
                    fields=[
                        ('id',
                         models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('message', models.CharField(max_length=180)),
                        ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first.post')),
                    ],
                ),
            ]
        ),
    ]
