# Generated by Django 3.2.8 on 2021-10-05 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('first', '0004_move_comment'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Comment',
                    fields=[
                        ('id',
                         models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('message', models.CharField(max_length=180)),
                        ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first.post')),
                    ],
                ),
            ]
        ),
    ]
