# Generated by Django 3.2.8 on 2021-10-06 20:35

from django.db import migrations

from system.migrations import MoveModelsMigration


class Migration(MoveModelsMigration):
    new_app_label = 'comments'

    dependencies = [
        ('first', '0003_alter_comment_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
