# Generated by Django 3.2.8 on 2021-10-05 11:49
from django.db import migrations, connection
from system.sql_generators import get_split_app_sql


def move_models_from_app(*args):
    with connection.cursor() as cursor:
        cursor.execute(get_split_app_sql(
            model_names=[
                'comment'
            ],
            old_app='first',
            new_app='comments',
        ))


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_alter_comment_message'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(move_models_from_app),
            ],
            state_operations=[
                migrations.DeleteModel(name='Comment'),
            ],
        )
    ]
