# Generated by Django 3.2.8 on 2021-10-05 11:49

from django.db import migrations


def get_rename_sql(model_names: [str], old_app: str, new_app: str):
    old_app = old_app.lower()
    new_app = new_app.lower()
    sql = ''
    for model in set(model_names):
        model = model.lower()
        sql += f'ALTER TABLE {old_app}_{model} RENAME TO {new_app}_{model};\n'
    return sql


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_alter_comment_message'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(get_rename_sql(['comment'], 'first', 'comments')),
            ],
            state_operations=[
                migrations.DeleteModel(name='Comment'),
            ],
        )
    ]
